version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: next
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      n8n-manager:
        patterns:
          - "@n8n-as-code/n8n-manager*"
          - "@n8n-as-code/n8n-credentials-manager"
    commit-message:
      prefix: "fix"
      include: "scope"
